### ISSUE TITLE
error,

### ISSUE THREAD

**Issue by axe-z** [AlexandreBonaventure/copy-es6-import#2]
"Copy ES6 Import" command
    has no effect when no files are open ?

I've got many open files, 
Jte devais une bière, mais là ... ;)

**Comment by AlexandreBonaventure** [comment]
C'est fixé dans la nouvelle version.
Alors c'est pour quand cette bière ? ce week-end ? :°

**Comment by axe-z** [comment]
Quand tu veux , j suis libre, si tu torches en Redux, j ai des questions ! ;)

**Comment by axe-z** [comment]
ahh j pense que t es pas dans react toi hein, mais plus Vue... si seulement Vue avait un truc comme react Native..

**Comment by axe-z** [comment]
Oh j avais ton email, 
Salut Alexandre, 

J’vais t expliquer mon affaire, si jamais tu peux m'aider tant mieux, sinon pas grave mais j annule ma dette de biere ;) 
J suis un quasi novice… j faisais bcp de flash, action script 2 (pas 3 ), et pendant des annees , decenie meme et j ai tout lacher avec l arrivé du iphone….  j avais jamais fait d html encore moins de css… sinon de centrer mon site flash.
j faisais bcp plus de branding print qu autre choses

J ai eu une blessure y a 2 ans , et j ai du arreter de travailler ( 2 hernies discales lombaire) , et j avais pas le gout de m emmerder, donc j me suis mis a me mettre a jour. 
J ai appris html , css, un peu de phh pour me rendre compte que le future etait en JS , bien que fucking wordpress semble partout. apres es5 - jquery-  ensuite es6, J ai commencer par backbone , pour finalement aller sur react, que je comprend bien avec redux. Je vois que t es avec Vue, j me demande encore la si ca vaut la peine vs react, etant donne  le temps que j y ai mis deja. 

Mais la pour le back end , je rush, express, mongo, mongoose, firebase, Apollo, y a tellement d’affaire…  j my perd. 

Tu me conseilles d apprendre quoi a fond rendu la , mon front-end est pas pire, mon back end c’est une autre histoire. quoi éviter , quoi persister et m obstiner a essayer de comprendre. 
 
Tu me connais pas, tu me dois rien, en fait la dette est deja de mon bord, mais voila ta chance de passer au whisky ;) 

Ben
514 886 2650

**Comment by AlexandreBonaventure** [comment]
Salut, 
Pourquoi pas discuter de ça autour d’une bière? Moi je suis en congé paternité donc c’est quand tu veux. Demain , il y a js-montréal dans le Mile-end on pourrait aller se boire une bière vers 17h puis aller ensuite à la conférence.

Au plaisir.
ps: donne-moi ton mail.

**Comment by axe-z** [comment]
Ah ca serait vraiment cool, je connais pas js-montreal ,  j ai rien de prevu du tout demain donc ca me va , j habite près du parc laurier. je sais pas comment tu veux qu on s organise, mais n importe quoi qui peut m aider , j vais le prendre. 
benoitlafrance@gmail.com <mailto:benoitlafrance@gmail.com>

**Comment by axe-z** [comment]
Je sais pas si tu m a bloquer par texto, mais ouff, tu me dois vraiment rien, c est clair, mais t avais ramené mon espoir en l humanité mais pour seulement ensuite rapidement la remmetre a sa place…

weird.
